// Historic NBA Standings - 2025-26 Season
// Source: Basketball Reference
// Complete daily standings from season start through Nov 17, 2025

export const DAILY_STANDINGS = {
  "2025-10-22": {
    East: [
      { team: "Bulls", w: 1, l: 0 },
      { team: "Hornets", w: 1, l: 0 },
      { team: "Bucks", w: 1, l: 0 },
      { team: "Knicks", w: 1, l: 0 },
      { team: "Magic", w: 1, l: 0 },
      { team: "76ers", w: 1, l: 0 },
      { team: "Raptors", w: 1, l: 0 },
      { team: "Hawks", w: 0, l: 1 },
      { team: "Celtics", w: 0, l: 1 },
      { team: "Nets", w: 0, l: 1 },
      { team: "Cavaliers", w: 0, l: 1 },
      { team: "Pistons", w: 0, l: 1 },
      { team: "Heat", w: 0, l: 1 },
      { team: "Wizards", w: 0, l: 1 },
      { team: "Pacers", w: 0, l: 1 }
    ],
    West: [
      { team: "Warriors", w: 1, l: 0 },
      { team: "Grizzlies", w: 1, l: 0 },
      { team: "Timberwolves", w: 1, l: 0 },
      { team: "Thunder", w: 1, l: 0 },
      { team: "Suns", w: 1, l: 0 },
      { team: "Spurs", w: 1, l: 0 },
      { team: "Jazz", w: 1, l: 0 },
      { team: "Mavericks", w: 0, l: 1 },
      { team: "Rockets", w: 0, l: 1 },
      { team: "Clippers", w: 0, l: 1 },
      { team: "Lakers", w: 0, l: 1 },
      { team: "Pelicans", w: 0, l: 1 },
      { team: "Trail Blazers", w: 0, l: 1 },
      { team: "Kings", w: 0, l: 1 },
      { team: "Nuggets", w: 0, l: 0 }
    ]
  },

  "2025-10-23": {
    East: [
      { team: "Bulls", w: 1, l: 0 },
      { team: "Hornets", w: 1, l: 0 },
      { team: "Bucks", w: 1, l: 0 },
      { team: "Knicks", w: 1, l: 0 },
      { team: "Magic", w: 1, l: 0 },
      { team: "76ers", w: 1, l: 0 },
      { team: "Raptors", w: 1, l: 0 },
      { team: "Hawks", w: 0, l: 1 },
      { team: "Celtics", w: 0, l: 1 },
      { team: "Nets", w: 0, l: 1 },
      { team: "Cavaliers", w: 0, l: 1 },
      { team: "Pistons", w: 0, l: 1 },
      { team: "Heat", w: 0, l: 1 },
      { team: "Wizards", w: 0, l: 1 },
      { team: "Pacers", w: 0, l: 1 }
    ],
    West: [
      { team: "Warriors", w: 1, l: 0 },
      { team: "Grizzlies", w: 1, l: 0 },
      { team: "Timberwolves", w: 1, l: 0 },
      { team: "Thunder", w: 1, l: 0 },
      { team: "Suns", w: 1, l: 0 },
      { team: "Spurs", w: 1, l: 0 },
      { team: "Jazz", w: 1, l: 0 },
      { team: "Mavericks", w: 0, l: 1 },
      { team: "Rockets", w: 0, l: 1 },
      { team: "Clippers", w: 0, l: 1 },
      { team: "Lakers", w: 0, l: 1 },
      { team: "Pelicans", w: 0, l: 1 },
      { team: "Trail Blazers", w: 0, l: 1 },
      { team: "Kings", w: 0, l: 1 },
      { team: "Nuggets", w: 0, l: 0 }
    ]
  },

  "2025-10-24": {
    East: [
      { team: "Bucks", w: 2, l: 0 },
      { team: "Knicks", w: 2, l: 0 },
      { team: "Bulls", w: 1, l: 0 },
      { team: "Hornets", w: 1, l: 0 },
      { team: "76ers", w: 1, l: 0 },
      { team: "Hawks", w: 1, l: 1 },
      { team: "Cavaliers", w: 1, l: 1 },
      { team: "Pistons", w: 1, l: 1 },
      { team: "Heat", w: 1, l: 1 },
      { team: "Magic", w: 1, l: 1 },
      { team: "Raptors", w: 1, l: 1 },
      { team: "Wizards", w: 1, l: 1 },
      { team: "Celtics", w: 0, l: 2 },
      { team: "Nets", w: 0, l: 2 },
      { team: "Pacers", w: 0, l: 1 }
    ],
    West: [
      { team: "Thunder", w: 2, l: 0 },
      { team: "Spurs", w: 2, l: 0 },
      { team: "Warriors", w: 2, l: 1 },
      { team: "Clippers", w: 1, l: 1 },
      { team: "Lakers", w: 1, l: 1 },
      { team: "Grizzlies", w: 1, l: 1 },
      { team: "Timberwolves", w: 1, l: 1 },
      { team: "Suns", w: 1, l: 1 },
      { team: "Trail Blazers", w: 1, l: 1 },
      { team: "Kings", w: 1, l: 1 },
      { team: "Jazz", w: 1, l: 1 },
      { team: "Mavericks", w: 0, l: 2 },
      { team: "Nuggets", w: 0, l: 1 },
      { team: "Rockets", w: 0, l: 2 },
      { team: "Pelicans", w: 0, l: 2 }
    ]
  },

  "2025-10-25": {
    East: [
      { team: "Bulls", w: 2, l: 0 },
      { team: "Bucks", w: 2, l: 0 },
      { team: "Knicks", w: 2, l: 0 },
      { team: "76ers", w: 2, l: 0 },
      { team: "Hornets", w: 1, l: 1 },
      { team: "Cavaliers", w: 1, l: 1 },
      { team: "Pistons", w: 1, l: 1 },
      { team: "Heat", w: 1, l: 1 },
      { team: "Raptors", w: 1, l: 1 },
      { team: "Wizards", w: 1, l: 1 },
      { team: "Hawks", w: 1, l: 2 },
      { team: "Magic", w: 1, l: 2 },
      { team: "Celtics", w: 0, l: 2 },
      { team: "Nets", w: 0, l: 2 },
      { team: "Pacers", w: 0, l: 2 }
    ],
    West: [
      { team: "Thunder", w: 2, l: 0 },
      { team: "Spurs", w: 2, l: 0 },
      { team: "Warriors", w: 2, l: 1 },
      { team: "Clippers", w: 1, l: 1 },
      { team: "Lakers", w: 1, l: 1 },
      { team: "Grizzlies", w: 1, l: 1 },
      { team: "Timberwolves", w: 1, l: 1 },
      { team: "Suns", w: 1, l: 1 },
      { team: "Trail Blazers", w: 1, l: 1 },
      { team: "Kings", w: 1, l: 1 },
      { team: "Jazz", w: 1, l: 1 },
      { team: "Mavericks", w: 0, l: 2 },
      { team: "Nuggets", w: 0, l: 1 },
      { team: "Rockets", w: 0, l: 2 },
      { team: "Pelicans", w: 0, l: 2 }
    ]
  },

  "2025-10-26": {
    East: [
      { team: "Bulls", w: 2, l: 0 },
      { team: "76ers", w: 2, l: 0 },
      { team: "Hornets", w: 2, l: 1 },
      { team: "Cavaliers", w: 2, l: 1 },
      { team: "Pistons", w: 2, l: 1 },
      { team: "Heat", w: 2, l: 1 },
      { team: "Bucks", w: 2, l: 1 },
      { team: "Knicks", w: 2, l: 1 },
      { team: "Hawks", w: 1, l: 2 },
      { team: "Magic", w: 1, l: 2 },
      { team: "Raptors", w: 1, l: 2 },
      { team: "Wizards", w: 1, l: 2 },
      { team: "Celtics", w: 0, l: 3 },
      { team: "Nets", w: 0, l: 3 },
      { team: "Pacers", w: 0, l: 3 }
    ],
    West: [
      { team: "Thunder", w: 2, l: 0 },
      { team: "Spurs", w: 2, l: 0 },
      { team: "Warriors", w: 2, l: 1 },
      { team: "Clippers", w: 1, l: 1 },
      { team: "Lakers", w: 1, l: 1 },
      { team: "Grizzlies", w: 1, l: 1 },
      { team: "Timberwolves", w: 1, l: 1 },
      { team: "Suns", w: 1, l: 1 },
      { team: "Trail Blazers", w: 1, l: 1 },
      { team: "Kings", w: 1, l: 1 },
      { team: "Jazz", w: 1, l: 1 },
      { team: "Mavericks", w: 0, l: 2 },
      { team: "Nuggets", w: 0, l: 1 },
      { team: "Rockets", w: 0, l: 2 },
      { team: "Pelicans", w: 0, l: 2 }
    ]
  },

  "2025-10-27": {
    East: [
      { team: "Bulls", w: 3, l: 0 },
      { team: "76ers", w: 3, l: 0 },
      { team: "Cavaliers", w: 3, l: 1 },
      { team: "Hornets", w: 2, l: 1 },
      { team: "Heat", w: 2, l: 1 },
      { team: "Bucks", w: 2, l: 1 },
      { team: "Knicks", w: 2, l: 1 },
      { team: "Pistons", w: 2, l: 2 },
      { team: "Wizards", w: 1, l: 2 },
      { team: "Hawks", w: 1, l: 3 },
      { team: "Celtics", w: 1, l: 3 },
      { team: "Magic", w: 1, l: 3 },
      { team: "Raptors", w: 1, l: 3 },
      { team: "Nets", w: 0, l: 4 },
      { team: "Pacers", w: 0, l: 3 }
    ],
    West: [
      { team: "Thunder", w: 3, l: 0 },
      { team: "Spurs", w: 3, l: 0 },
      { team: "Warriors", w: 3, l: 1 },
      { team: "Nuggets", w: 1, l: 1 },
      { team: "Clippers", w: 1, l: 2 },
      { team: "Lakers", w: 1, l: 2 },
      { team: "Grizzlies", w: 1, l: 2 },
      { team: "Timberwolves", w: 1, l: 2 },
      { team: "Suns", w: 1, l: 2 },
      { team: "Trail Blazers", w: 1, l: 2 },
      { team: "Kings", w: 1, l: 2 },
      { team: "Jazz", w: 1, l: 2 },
      { team: "Mavericks", w: 0, l: 3 },
      { team: "Rockets", w: 0, l: 3 },
      { team: "Pelicans", w: 0, l: 3 }
    ]
  },

  "2025-10-28": {
    East: [
      { team: "76ers", w: 4, l: 0 },
      { team: "Bulls", w: 3, l: 0 },
      { team: "Cavaliers", w: 3, l: 1 },
      { team: "Heat", w: 3, l: 1 },
      { team: "Bucks", w: 3, l: 1 },
      { team: "Hornets", w: 2, l: 2 },
      { team: "Pistons", w: 2, l: 2 },
      { team: "Knicks", w: 2, l: 2 },
      { team: "Hawks", w: 1, l: 3 },
      { team: "Celtics", w: 1, l: 3 },
      { team: "Magic", w: 1, l: 3 },
      { team: "Raptors", w: 1, l: 3 },
      { team: "Wizards", w: 1, l: 3 },
      { team: "Nets", w: 0, l: 4 },
      { team: "Pacers", w: 0, l: 3 }
    ],
    West: [
      { team: "Thunder", w: 4, l: 0 },
      { team: "Spurs", w: 4, l: 0 },
      { team: "Warriors", w: 4, l: 1 },
      { team: "Nuggets", w: 2, l: 1 },
      { team: "Lakers", w: 2, l: 2 },
      { team: "Rockets", w: 1, l: 3 },
      { team: "Clippers", w: 1, l: 3 },
      { team: "Grizzlies", w: 1, l: 3 },
      { team: "Timberwolves", w: 1, l: 3 },
      { team: "Suns", w: 1, l: 3 },
      { team: "Trail Blazers", w: 1, l: 3 },
      { team: "Kings", w: 1, l: 3 },
      { team: "Jazz", w: 1, l: 3 },
      { team: "Mavericks", w: 0, l: 4 },
      { team: "Pelicans", w: 0, l: 4 }
    ]
  },

  "2025-10-29": {
    East: [
      { team: "Bulls", w: 4, l: 0 },
      { team: "76ers", w: 4, l: 0 },
      { team: "Heat", w: 3, l: 1 },
      { team: "Bucks", w: 3, l: 1 },
      { team: "Cavaliers", w: 3, l: 2 },
      { team: "Pistons", w: 3, l: 2 },
      { team: "Hornets", w: 2, l: 2 },
      { team: "Knicks", w: 2, l: 2 },
      { team: "Hawks", w: 2, l: 3 },
      { team: "Celtics", w: 2, l: 3 },
      { team: "Wizards", w: 1, l: 3 },
      { team: "Magic", w: 1, l: 4 },
      { team: "Raptors", w: 1, l: 4 },
      { team: "Nets", w: 0, l: 5 },
      { team: "Pacers", w: 0, l: 4 }
    ],
    West: [
      { team: "Thunder", w: 5, l: 0 },
      { team: "Spurs", w: 5, l: 0 },
      { team: "Warriors", w: 4, l: 1 },
      { team: "Nuggets", w: 3, l: 1 },
      { team: "Lakers", w: 3, l: 2 },
      { team: "Suns", w: 2, l: 2 },
      { team: "Rockets", w: 2, l: 3 },
      { team: "Clippers", w: 2, l: 3 },
      { team: "Grizzlies", w: 2, l: 3 },
      { team: "Timberwolves", w: 2, l: 3 },
      { team: "Trail Blazers", w: 2, l: 3 },
      { team: "Kings", w: 1, l: 3 },
      { team: "Jazz", w: 1, l: 4 },
      { team: "Mavericks", w: 0, l: 4 },
      { team: "Pelicans", w: 0, l: 4 }
    ]
  },

  "2025-10-30": {
    East: [
      { team: "Bulls", w: 4, l: 0 },
      { team: "76ers", w: 4, l: 0 },
      { team: "Bucks", w: 4, l: 1 },
      { team: "Cavaliers", w: 3, l: 2 },
      { team: "Pistons", w: 3, l: 2 },
      { team: "Heat", w: 3, l: 2 },
      { team: "Knicks", w: 2, l: 2 },
      { team: "Hawks", w: 2, l: 3 },
      { team: "Celtics", w: 2, l: 3 },
      { team: "Hornets", w: 2, l: 3 },
      { team: "Magic", w: 2, l: 4 },
      { team: "Raptors", w: 1, l: 4 },
      { team: "Wizards", w: 1, l: 4 },
      { team: "Nets", w: 0, l: 5 },
      { team: "Pacers", w: 0, l: 4 }
    ],
    West: [
      { team: "Thunder", w: 6, l: 0 },
      { team: "Spurs", w: 5, l: 0 },
      { team: "Warriors", w: 4, l: 2 },
      { team: "Lakers", w: 4, l: 2 },
      { team: "Trail Blazers", w: 4, l: 2 },
      { team: "Nuggets", w: 3, l: 2 },
      { team: "Clippers", w: 3, l: 2 },
      { team: "Grizzlies", w: 3, l: 3 },
      { team: "Rockets", w: 2, l: 2 },
      { team: "Mavericks", w: 2, l: 3 },
      { team: "Timberwolves", w: 2, l: 3 },
      { team: "Jazz", w: 2, l: 3 },
      { team: "Suns", w: 2, l: 4 },
      { team: "Kings", w: 1, l: 4 },
      { team: "Pelicans", w: 0, l: 5 }
    ]
  },

  "2025-10-31": {
    East: [
      { team: "Bulls", w: 5, l: 0 },
      { team: "Bucks", w: 4, l: 1 },
      { team: "76ers", w: 4, l: 1 },
      { team: "Pistons", w: 3, l: 2 },
      { team: "Heat", w: 3, l: 2 },
      { team: "Hawks", w: 3, l: 3 },
      { team: "Celtics", w: 3, l: 3 },
      { team: "Cavaliers", w: 3, l: 3 },
      { team: "Hornets", w: 2, l: 3 },
      { team: "Knicks", w: 2, l: 3 },
      { team: "Magic", w: 2, l: 4 },
      { team: "Raptors", w: 2, l: 4 },
      { team: "Wizards", w: 1, l: 4 },
      { team: "Nets", w: 0, l: 5 },
      { team: "Pacers", w: 0, l: 5 }
    ],
    West: [
      { team: "Thunder", w: 6, l: 0 },
      { team: "Spurs", w: 5, l: 0 },
      { team: "Warriors", w: 4, l: 2 },
      { team: "Lakers", w: 4, l: 2 },
      { team: "Trail Blazers", w: 4, l: 2 },
      { team: "Nuggets", w: 3, l: 2 },
      { team: "Clippers", w: 3, l: 2 },
      { team: "Grizzlies", w: 3, l: 3 },
      { team: "Rockets", w: 2, l: 2 },
      { team: "Mavericks", w: 2, l: 3 },
      { team: "Timberwolves", w: 2, l: 3 },
      { team: "Jazz", w: 2, l: 3 },
      { team: "Suns", w: 2, l: 4 },
      { team: "Kings", w: 1, l: 4 },
      { team: "Pelicans", w: 0, l: 5 }
    ]
  },

  "2025-11-01": {
    East: [
      { team: "Bulls", w: 5, l: 0 },
      { team: "76ers", w: 4, l: 1 },
      { team: "Pistons", w: 4, l: 2 },
      { team: "Bucks", w: 4, l: 2 },
      { team: "Heat", w: 3, l: 2 },
      { team: "Hawks", w: 3, l: 3 },
      { team: "Cavaliers", w: 3, l: 3 },
      { team: "Celtics", w: 3, l: 4 },
      { team: "Magic", w: 3, l: 4 },
      { team: "Knicks", w: 2, l: 3 },
      { team: "Hornets", w: 2, l: 4 },
      { team: "Raptors", w: 2, l: 4 },
      { team: "Pacers", w: 1, l: 5 },
      { team: "Wizards", w: 1, l: 5 },
      { team: "Nets", w: 0, l: 5 }
    ],
    West: [
      { team: "Thunder", w: 7, l: 0 },
      { team: "Spurs", w: 6, l: 0 },
      { team: "Warriors", w: 5, l: 2 },
      { team: "Lakers", w: 5, l: 2 },
      { team: "Trail Blazers", w: 5, l: 2 },
      { team: "Nuggets", w: 4, l: 2 },
      { team: "Rockets", w: 3, l: 2 },
      { team: "Clippers", w: 4, l: 2 },
      { team: "Grizzlies", w: 3, l: 3 },
      { team: "Timberwolves", w: 3, l: 3 },
      { team: "Mavericks", w: 2, l: 3 },
      { team: "Jazz", w: 2, l: 4 },
      { team: "Suns", w: 2, l: 4 },
      { team: "Kings", w: 1, l: 5 },
      { team: "Pelicans", w: 0, l: 6 }
    ]
  },

  "2025-11-02": {
    East: [
      { team: "Bulls", w: 5, l: 1 },
      { team: "76ers", w: 5, l: 1 },
      { team: "Pistons", w: 4, l: 2 },
      { team: "Bucks", w: 4, l: 2 },
      { team: "Cavaliers", w: 4, l: 3 },
      { team: "Heat", w: 3, l: 3 },
      { team: "Knicks", w: 3, l: 3 },
      { team: "Hawks", w: 3, l: 4 },
      { team: "Celtics", w: 3, l: 4 },
      { team: "Hornets", w: 3, l: 4 },
      { team: "Magic", w: 3, l: 4 },
      { team: "Raptors", w: 3, l: 4 },
      { team: "Pacers", w: 1, l: 5 },
      { team: "Wizards", w: 1, l: 5 },
      { team: "Nets", w: 0, l: 6 }
    ],
    West: [
      { team: "Thunder", w: 8, l: 0 },
      { team: "Spurs", w: 7, l: 0 },
      { team: "Warriors", w: 6, l: 2 },
      { team: "Lakers", w: 6, l: 2 },
      { team: "Trail Blazers", w: 6, l: 2 },
      { team: "Nuggets", w: 5, l: 2 },
      { team: "Rockets", w: 4, l: 2 },
      { team: "Clippers", w: 4, l: 3 },
      { team: "Grizzlies", w: 4, l: 3 },
      { team: "Timberwolves", w: 4, l: 3 },
      { team: "Mavericks", w: 3, l: 3 },
      { team: "Jazz", w: 2, l: 4 },
      { team: "Suns", w: 2, l: 5 },
      { team: "Kings", w: 1, l: 5 },
      { team: "Pelicans", w: 1, l: 6 }
    ]
  },

  "2025-11-03": {
    East: [
      { team: "Bulls", w: 5, l: 1 },
      { team: "76ers", w: 5, l: 1 },
      { team: "Pistons", w: 5, l: 2 },
      { team: "Bucks", w: 5, l: 2 },
      { team: "Cavaliers", w: 4, l: 3 },
      { team: "Heat", w: 4, l: 3 },
      { team: "Knicks", w: 4, l: 3 },
      { team: "Hawks", w: 3, l: 4 },
      { team: "Hornets", w: 3, l: 4 },
      { team: "Magic", w: 3, l: 4 },
      { team: "Raptors", w: 3, l: 4 },
      { team: "Celtics", w: 3, l: 5 },
      { team: "Pacers", w: 1, l: 6 },
      { team: "Wizards", w: 1, l: 6 },
      { team: "Nets", w: 0, l: 7 }
    ],
    West: [
      { team: "Thunder", w: 9, l: 0 },
      { team: "Spurs", w: 8, l: 0 },
      { team: "Warriors", w: 7, l: 2 },
      { team: "Lakers", w: 7, l: 2 },
      { team: "Nuggets", w: 6, l: 2 },
      { team: "Rockets", w: 5, l: 2 },
      { team: "Trail Blazers", w: 6, l: 3 },
      { team: "Clippers", w: 4, l: 4 },
      { team: "Grizzlies", w: 4, l: 4 },
      { team: "Timberwolves", w: 4, l: 4 },
      { team: "Mavericks", w: 3, l: 4 },
      { team: "Jazz", w: 3, l: 4 },
      { team: "Suns", w: 2, l: 5 },
      { team: "Kings", w: 2, l: 5 },
      { team: "Pelicans", w: 1, l: 7 }
    ]
  },

  "2025-11-04": {
    East: [
      { team: "Bulls", w: 6, l: 1 },
      { team: "Pistons", w: 5, l: 2 },
      { team: "76ers", w: 5, l: 2 },
      { team: "Bucks", w: 5, l: 3 },
      { team: "Cavaliers", w: 4, l: 3 },
      { team: "Heat", w: 4, l: 3 },
      { team: "Knicks", w: 4, l: 3 },
      { team: "Hawks", w: 4, l: 4 },
      { team: "Raptors", w: 4, l: 4 },
      { team: "Celtics", w: 3, l: 5 },
      { team: "Hornets", w: 3, l: 5 },
      { team: "Magic", w: 3, l: 5 },
      { team: "Pacers", w: 1, l: 6 },
      { team: "Wizards", w: 1, l: 6 },
      { team: "Nets", w: 0, l: 7 }
    ],
    West: [
      { team: "Thunder", w: 10, l: 0 },
      { team: "Spurs", w: 8, l: 1 },
      { team: "Warriors", w: 8, l: 2 },
      { team: "Lakers", w: 8, l: 2 },
      { team: "Nuggets", w: 7, l: 2 },
      { team: "Rockets", w: 6, l: 2 },
      { team: "Trail Blazers", w: 6, l: 3 },
      { team: "Timberwolves", w: 5, l: 4 },
      { team: "Clippers", w: 4, l: 4 },
      { team: "Grizzlies", w: 4, l: 4 },
      { team: "Mavericks", w: 3, l: 4 },
      { team: "Jazz", w: 3, l: 5 },
      { team: "Suns", w: 2, l: 5 },
      { team: "Kings", w: 2, l: 6 },
      { team: "Pelicans", w: 1, l: 7 }
    ]
  },

  "2025-11-05": {
    East: [
      { team: "Bulls", w: 6, l: 1 },
      { team: "Pistons", w: 6, l: 2 },
      { team: "Cavaliers", w: 5, l: 3 },
      { team: "Bucks", w: 5, l: 3 },
      { team: "Knicks", w: 5, l: 3 },
      { team: "76ers", w: 5, l: 3 },
      { team: "Hawks", w: 4, l: 4 },
      { team: "Heat", w: 4, l: 4 },
      { team: "Raptors", w: 4, l: 4 },
      { team: "Celtics", w: 4, l: 5 },
      { team: "Hornets", w: 3, l: 5 },
      { team: "Magic", w: 3, l: 5 },
      { team: "Nets", w: 1, l: 7 },
      { team: "Pacers", w: 1, l: 7 },
      { team: "Wizards", w: 1, l: 7 }
    ],
    West: [
      { team: "Thunder", w: 11, l: 0 },
      { team: "Spurs", w: 9, l: 1 },
      { team: "Warriors", w: 9, l: 2 },
      { team: "Lakers", w: 9, l: 2 },
      { team: "Nuggets", w: 8, l: 2 },
      { team: "Rockets", w: 7, l: 2 },
      { team: "Trail Blazers", w: 6, l: 4 },
      { team: "Timberwolves", w: 6, l: 4 },
      { team: "Grizzlies", w: 5, l: 4 },
      { team: "Clippers", w: 4, l: 5 },
      { team: "Mavericks", w: 3, l: 5 },
      { team: "Jazz", w: 3, l: 5 },
      { team: "Suns", w: 2, l: 6 },
      { team: "Kings", w: 2, l: 6 },
      { team: "Pelicans", w: 1, l: 8 }
    ]
  },

  "2025-11-06": {
    East: [
      { team: "Bulls", w: 6, l: 1 },
      { team: "Pistons", w: 6, l: 2 },
      { team: "Cavaliers", w: 5, l: 3 },
      { team: "Bucks", w: 5, l: 3 },
      { team: "Knicks", w: 5, l: 3 },
      { team: "76ers", w: 5, l: 3 },
      { team: "Hawks", w: 4, l: 4 },
      { team: "Heat", w: 4, l: 4 },
      { team: "Raptors", w: 4, l: 4 },
      { team: "Celtics", w: 4, l: 5 },
      { team: "Hornets", w: 3, l: 5 },
      { team: "Magic", w: 3, l: 5 },
      { team: "Nets", w: 1, l: 7 },
      { team: "Pacers", w: 1, l: 7 },
      { team: "Wizards", w: 1, l: 7 }
    ],
    West: [
      { team: "Thunder", w: 11, l: 0 },
      { team: "Spurs", w: 9, l: 1 },
      { team: "Warriors", w: 9, l: 2 },
      { team: "Lakers", w: 9, l: 2 },
      { team: "Nuggets", w: 8, l: 2 },
      { team: "Rockets", w: 7, l: 2 },
      { team: "Trail Blazers", w: 6, l: 4 },
      { team: "Timberwolves", w: 6, l: 4 },
      { team: "Grizzlies", w: 5, l: 4 },
      { team: "Clippers", w: 4, l: 5 },
      { team: "Mavericks", w: 3, l: 5 },
      { team: "Jazz", w: 3, l: 5 },
      { team: "Suns", w: 2, l: 6 },
      { team: "Kings", w: 2, l: 6 },
      { team: "Pelicans", w: 1, l: 8 }
    ]
  },

  "2025-11-07": {
    East: [
      { team: "Pistons", w: 7, l: 2 },
      { team: "Bulls", w: 6, l: 2 },
      { team: "Cavaliers", w: 6, l: 3 },
      { team: "Bucks", w: 6, l: 3 },
      { team: "Knicks", w: 5, l: 3 },
      { team: "76ers", w: 5, l: 3 },
      { team: "Heat", w: 5, l: 4 },
      { team: "Raptors", w: 5, l: 4 },
      { team: "Hawks", w: 4, l: 5 },
      { team: "Magic", w: 4, l: 5 },
      { team: "Celtics", w: 4, l: 6 },
      { team: "Hornets", w: 3, l: 6 },
      { team: "Pacers", w: 1, l: 7 },
      { team: "Nets", w: 1, l: 8 },
      { team: "Wizards", w: 1, l: 8 }
    ],
    West: [
      { team: "Thunder", w: 12, l: 0 },
      { team: "Spurs", w: 10, l: 1 },
      { team: "Warriors", w: 10, l: 2 },
      { team: "Lakers", w: 10, l: 2 },
      { team: "Nuggets", w: 9, l: 2 },
      { team: "Rockets", w: 8, l: 2 },
      { team: "Timberwolves", w: 7, l: 4 },
      { team: "Trail Blazers", w: 6, l: 5 },
      { team: "Grizzlies", w: 5, l: 5 },
      { team: "Clippers", w: 4, l: 6 },
      { team: "Jazz", w: 4, l: 5 },
      { team: "Mavericks", w: 3, l: 6 },
      { team: "Suns", w: 3, l: 6 },
      { team: "Kings", w: 2, l: 7 },
      { team: "Pelicans", w: 1, l: 9 }
    ]
  },

  "2025-11-08": {
    East: [
      { team: "Pistons", w: 7, l: 2 },
      { team: "Cavaliers", w: 7, l: 3 },
      { team: "Bulls", w: 6, l: 3 },
      { team: "Bucks", w: 6, l: 3 },
      { team: "76ers", w: 6, l: 3 },
      { team: "Knicks", w: 5, l: 3 },
      { team: "Heat", w: 6, l: 4 },
      { team: "Hawks", w: 5, l: 5 },
      { team: "Raptors", w: 5, l: 5 },
      { team: "Magic", w: 4, l: 5 },
      { team: "Celtics", w: 4, l: 6 },
      { team: "Hornets", w: 3, l: 6 },
      { team: "Nets", w: 1, l: 8 },
      { team: "Pacers", w: 1, l: 8 },
      { team: "Wizards", w: 1, l: 9 }
    ],
    West: [
      { team: "Thunder", w: 13, l: 0 },
      { team: "Spurs", w: 11, l: 1 },
      { team: "Warriors", w: 11, l: 2 },
      { team: "Lakers", w: 11, l: 2 },
      { team: "Nuggets", w: 10, l: 2 },
      { team: "Rockets", w: 9, l: 2 },
      { team: "Timberwolves", w: 8, l: 4 },
      { team: "Trail Blazers", w: 6, l: 6 },
      { team: "Grizzlies", w: 5, l: 6 },
      { team: "Suns", w: 4, l: 6 },
      { team: "Jazz", w: 4, l: 6 },
      { team: "Clippers", w: 4, l: 7 },
      { team: "Mavericks", w: 3, l: 7 },
      { team: "Kings", w: 2, l: 8 },
      { team: "Pelicans", w: 1, l: 10 }
    ]
  },

  "2025-11-09": {
    East: [
      { team: "Pistons", w: 8, l: 2 },
      { team: "Cavaliers", w: 7, l: 3 },
      { team: "Bulls", w: 6, l: 3 },
      { team: "Knicks", w: 6, l: 3 },
      { team: "Heat", w: 6, l: 4 },
      { team: "Bucks", w: 6, l: 4 },
      { team: "76ers", w: 6, l: 4 },
      { team: "Hawks", w: 5, l: 5 },
      { team: "Raptors", w: 5, l: 5 },
      { team: "Celtics", w: 5, l: 6 },
      { team: "Magic", w: 4, l: 6 },
      { team: "Hornets", w: 3, l: 6 },
      { team: "Nets", w: 1, l: 9 },
      { team: "Pacers", w: 1, l: 9 },
      { team: "Wizards", w: 1, l: 9 }
    ],
    West: [
      { team: "Thunder", w: 14, l: 0 },
      { team: "Spurs", w: 11, l: 2 },
      { team: "Warriors", w: 11, l: 3 },
      { team: "Lakers", w: 11, l: 3 },
      { team: "Nuggets", w: 10, l: 3 },
      { team: "Rockets", w: 9, l: 3 },
      { team: "Timberwolves", w: 8, l: 5 },
      { team: "Trail Blazers", w: 6, l: 6 },
      { team: "Suns", w: 5, l: 6 },
      { team: "Grizzlies", w: 5, l: 7 },
      { team: "Jazz", w: 4, l: 7 },
      { team: "Clippers", w: 4, l: 8 },
      { team: "Mavericks", w: 3, l: 8 },
      { team: "Kings", w: 2, l: 9 },
      { team: "Pelicans", w: 1, l: 11 }
    ]
  },

  "2025-11-10": {
    East: [
      { team: "Pistons", w: 9, l: 2 },
      { team: "Knicks", w: 6, l: 3 },
      { team: "Cavaliers", w: 7, l: 4 },
      { team: "Heat", w: 7, l: 4 },
      { team: "Bucks", w: 7, l: 4 },
      { team: "Bulls", w: 6, l: 4 },
      { team: "76ers", w: 6, l: 4 },
      { team: "Hawks", w: 6, l: 5 },
      { team: "Raptors", w: 5, l: 5 },
      { team: "Celtics", w: 5, l: 6 },
      { team: "Magic", w: 5, l: 6 },
      { team: "Hornets", w: 3, l: 7 },
      { team: "Nets", w: 1, l: 9 },
      { team: "Pacers", w: 1, l: 9 },
      { team: "Wizards", w: 1, l: 10 }
    ],
    West: [
      { team: "Thunder", w: 14, l: 1 },
      { team: "Spurs", w: 11, l: 3 },
      { team: "Warriors", w: 11, l: 4 },
      { team: "Lakers", w: 11, l: 4 },
      { team: "Nuggets", w: 10, l: 4 },
      { team: "Rockets", w: 9, l: 4 },
      { team: "Timberwolves", w: 8, l: 6 },
      { team: "Suns", w: 6, l: 6 },
      { team: "Trail Blazers", w: 6, l: 7 },
      { team: "Grizzlies", w: 5, l: 8 },
      { team: "Jazz", w: 4, l: 8 },
      { team: "Clippers", w: 4, l: 9 },
      { team: "Mavericks", w: 3, l: 9 },
      { team: "Kings", w: 2, l: 10 },
      { team: "Pelicans", w: 1, l: 12 }
    ]
  },

  "2025-11-11": {
    East: [
      { team: "Pistons", w: 9, l: 2 },
      { team: "Knicks", w: 7, l: 3 },
      { team: "Cavaliers", w: 7, l: 4 },
      { team: "Heat", w: 7, l: 4 },
      { team: "Bucks", w: 7, l: 4 },
      { team: "76ers", w: 7, l: 4 },
      { team: "Bulls", w: 6, l: 4 },
      { team: "Hawks", w: 6, l: 5 },
      { team: "Raptors", w: 6, l: 5 },
      { team: "Magic", w: 5, l: 6 },
      { team: "Celtics", w: 5, l: 7 },
      { team: "Hornets", w: 3, l: 7 },
      { team: "Nets", w: 1, l: 10 },
      { team: "Pacers", w: 1, l: 10 },
      { team: "Wizards", w: 1, l: 10 }
    ],
    West: [
      { team: "Thunder", w: 14, l: 1 },
      { team: "Spurs", w: 11, l: 3 },
      { team: "Warriors", w: 11, l: 4 },
      { team: "Lakers", w: 11, l: 4 },
      { team: "Nuggets", w: 10, l: 4 },
      { team: "Rockets", w: 9, l: 4 },
      { team: "Timberwolves", w: 9, l: 6 },
      { team: "Suns", w: 7, l: 6 },
      { team: "Trail Blazers", w: 6, l: 7 },
      { team: "Jazz", w: 5, l: 8 },
      { team: "Grizzlies", w: 5, l: 8 },
      { team: "Clippers", w: 4, l: 9 },
      { team: "Mavericks", w: 3, l: 10 },
      { team: "Kings", w: 2, l: 10 },
      { team: "Pelicans", w: 1, l: 12 }
    ]
  },

  "2025-11-12": {
    East: [
      { team: "Pistons", w: 10, l: 2 },
      { team: "Cavaliers", w: 8, l: 4 },
      { team: "Knicks", w: 7, l: 4 },
      { team: "76ers", w: 7, l: 4 },
      { team: "Hawks", w: 7, l: 5 },
      { team: "Heat", w: 7, l: 5 },
      { team: "Bucks", w: 7, l: 5 },
      { team: "Bulls", w: 6, l: 5 },
      { team: "Raptors", w: 6, l: 5 },
      { team: "Magic", w: 6, l: 6 },
      { team: "Celtics", w: 6, l: 7 },
      { team: "Hornets", w: 4, l: 7 },
      { team: "Nets", w: 1, l: 10 },
      { team: "Pacers", w: 1, l: 10 },
      { team: "Wizards", w: 1, l: 11 }
    ],
    West: [
      { team: "Thunder", w: 14, l: 1 },
      { team: "Spurs", w: 11, l: 3 },
      { team: "Warriors", w: 11, l: 4 },
      { team: "Lakers", w: 11, l: 4 },
      { team: "Nuggets", w: 10, l: 4 },
      { team: "Rockets", w: 9, l: 4 },
      { team: "Timberwolves", w: 9, l: 6 },
      { team: "Suns", w: 8, l: 6 },
      { team: "Trail Blazers", w: 6, l: 7 },
      { team: "Jazz", w: 5, l: 8 },
      { team: "Grizzlies", w: 5, l: 8 },
      { team: "Clippers", w: 4, l: 10 },
      { team: "Mavericks", w: 4, l: 10 },
      { team: "Kings", w: 3, l: 10 },
      { team: "Pelicans", w: 2, l: 12 }
    ]
  },

  "2025-11-13": {
    East: [
      { team: "Pistons", w: 10, l: 2 },
      { team: "Knicks", w: 7, l: 4 },
      { team: "76ers", w: 7, l: 4 },
      { team: "Hawks", w: 8, l: 5 },
      { team: "Cavaliers", w: 8, l: 5 },
      { team: "Heat", w: 7, l: 5 },
      { team: "Bucks", w: 7, l: 5 },
      { team: "Raptors", w: 7, l: 5 },
      { team: "Bulls", w: 6, l: 5 },
      { team: "Magic", w: 6, l: 6 },
      { team: "Celtics", w: 6, l: 7 },
      { team: "Hornets", w: 4, l: 7 },
      { team: "Nets", w: 1, l: 10 },
      { team: "Pacers", w: 1, l: 11 },
      { team: "Wizards", w: 1, l: 11 }
    ],
    West: [
      { team: "Thunder", w: 14, l: 1 },
      { team: "Spurs", w: 11, l: 3 },
      { team: "Warriors", w: 11, l: 4 },
      { team: "Lakers", w: 11, l: 4 },
      { team: "Nuggets", w: 10, l: 4 },
      { team: "Rockets", w: 9, l: 4 },
      { team: "Timberwolves", w: 9, l: 6 },
      { team: "Suns", w: 8, l: 6 },
      { team: "Trail Blazers", w: 6, l: 7 },
      { team: "Jazz", w: 5, l: 8 },
      { team: "Grizzlies", w: 5, l: 8 },
      { team: "Clippers", w: 4, l: 10 },
      { team: "Mavericks", w: 4, l: 10 },
      { team: "Kings", w: 3, l: 10 },
      { team: "Pelicans", w: 2, l: 12 }
    ]
  },

  "2025-11-14": {
    East: [
      { team: "Pistons", w: 11, l: 2 },
      { team: "Knicks", w: 8, l: 4 },
      { team: "Hawks", w: 8, l: 5 },
      { team: "Cavaliers", w: 8, l: 5 },
      { team: "Bucks", w: 8, l: 5 },
      { team: "76ers", w: 7, l: 5 },
      { team: "Raptors", w: 7, l: 5 },
      { team: "Bulls", w: 6, l: 5 },
      { team: "Heat", w: 7, l: 6 },
      { team: "Magic", w: 7, l: 6 },
      { team: "Celtics", w: 6, l: 7 },
      { team: "Hornets", w: 4, l: 8 },
      { team: "Nets", w: 1, l: 11 },
      { team: "Pacers", w: 1, l: 11 },
      { team: "Wizards", w: 1, l: 11 }
    ],
    West: [
      { team: "Thunder", w: 14, l: 1 },
      { team: "Spurs", w: 11, l: 3 },
      { team: "Warriors", w: 11, l: 4 },
      { team: "Lakers", w: 11, l: 4 },
      { team: "Nuggets", w: 10, l: 4 },
      { team: "Rockets", w: 9, l: 4 },
      { team: "Timberwolves", w: 9, l: 6 },
      { team: "Suns", w: 8, l: 6 },
      { team: "Trail Blazers", w: 6, l: 7 },
      { team: "Jazz", w: 5, l: 8 },
      { team: "Grizzlies", w: 5, l: 9 },
      { team: "Clippers", w: 4, l: 10 },
      { team: "Mavericks", w: 4, l: 10 },
      { team: "Kings", w: 3, l: 11 },
      { team: "Pelicans", w: 2, l: 12 }
    ]
  },

  "2025-11-15": {
    East: [
      { team: "Pistons", w: 11, l: 2 },
      { team: "Knicks", w: 8, l: 4 },
      { team: "Cavaliers", w: 9, l: 5 },
      { team: "Hawks", w: 8, l: 5 },
      { team: "Raptors", w: 8, l: 5 },
      { team: "76ers", w: 7, l: 5 },
      { team: "Bucks", w: 8, l: 6 },
      { team: "Bulls", w: 6, l: 5 },
      { team: "Heat", w: 7, l: 6 },
      { team: "Magic", w: 7, l: 6 },
      { team: "Celtics", w: 6, l: 7 },
      { team: "Hornets", w: 4, l: 9 },
      { team: "Nets", w: 1, l: 11 },
      { team: "Wizards", w: 1, l: 11 },
      { team: "Pacers", w: 1, l: 12 }
    ],
    West: [
      { team: "Thunder", w: 14, l: 1 },
      { team: "Spurs", w: 11, l: 3 },
      { team: "Warriors", w: 11, l: 5 },
      { team: "Lakers", w: 11, l: 4 },
      { team: "Nuggets", w: 10, l: 4 },
      { team: "Rockets", w: 9, l: 4 },
      { team: "Timberwolves", w: 9, l: 6 },
      { team: "Suns", w: 8, l: 6 },
      { team: "Trail Blazers", w: 6, l: 7 },
      { team: "Jazz", w: 5, l: 8 },
      { team: "Grizzlies", w: 5, l: 9 },
      { team: "Clippers", w: 4, l: 10 },
      { team: "Mavericks", w: 4, l: 11 },
      { team: "Kings", w: 3, l: 11 },
      { team: "Pelicans", w: 2, l: 12 }
    ]
  },

  "2025-11-16": {
    East: [
      { team: "Pistons", w: 11, l: 2 },
      { team: "Knicks", w: 8, l: 4 },
      { team: "Hawks", w: 9, l: 5 },
      { team: "Cavaliers", w: 9, l: 5 },
      { team: "Raptors", w: 8, l: 5 },
      { team: "76ers", w: 7, l: 5 },
      { team: "Bucks", w: 8, l: 6 },
      { team: "Heat", w: 7, l: 6 },
      { team: "Celtics", w: 7, l: 7 },
      { team: "Magic", w: 7, l: 7 },
      { team: "Bulls", w: 6, l: 6 },
      { team: "Hornets", w: 4, l: 9 },
      { team: "Nets", w: 2, l: 11 },
      { team: "Pacers", w: 1, l: 12 },
      { team: "Wizards", w: 1, l: 12 }
    ],
    West: [
      { team: "Thunder", w: 14, l: 1 },
      { team: "Spurs", w: 11, l: 4 },
      { team: "Warriors", w: 11, l: 5 },
      { team: "Lakers", w: 11, l: 4 },
      { team: "Nuggets", w: 10, l: 4 },
      { team: "Rockets", w: 9, l: 4 },
      { team: "Timberwolves", w: 9, l: 6 },
      { team: "Suns", w: 8, l: 6 },
      { team: "Trail Blazers", w: 6, l: 7 },
      { team: "Jazz", w: 5, l: 8 },
      { team: "Grizzlies", w: 5, l: 9 },
      { team: "Clippers", w: 4, l: 10 },
      { team: "Mavericks", w: 4, l: 11 },
      { team: "Kings", w: 3, l: 11 },
      { team: "Pelicans", w: 2, l: 12 }
    ]
  },

  "2025-11-17": {
    East: [
      { team: "Pistons", w: 12, l: 2 },
      { team: "Cavaliers", w: 10, l: 5 },
      { team: "Hawks", w: 9, l: 5 },
      { team: "Raptors", w: 9, l: 5 },
      { team: "Knicks", w: 8, l: 5 },
      { team: "76ers", w: 8, l: 5 },
      { team: "Heat", w: 8, l: 6 },
      { team: "Bulls", w: 7, l: 6 },
      { team: "Bucks", w: 8, l: 7 },
      { team: "Celtics", w: 7, l: 7 },
      { team: "Magic", w: 7, l: 7 },
      { team: "Hornets", w: 4, l: 10 },
      { team: "Nets", w: 2, l: 11 },
      { team: "Wizards", w: 1, l: 12 },
      { team: "Pacers", w: 1, l: 13 }
    ],
    West: [
      { team: "Thunder", w: 14, l: 1 },
      { team: "Nuggets", w: 10, l: 3 },
      { team: "Rockets", w: 9, l: 3 },
      { team: "Lakers", w: 10, l: 4 },
      { team: "Spurs", w: 9, l: 4 },
      { team: "Timberwolves", w: 9, l: 5 },
      { team: "Warriors", w: 9, l: 6 },
      { team: "Suns", w: 8, l: 6 },
      { team: "Trail Blazers", w: 6, l: 7 },
      { team: "Jazz", w: 5, l: 8 },
      { team: "Clippers", w: 4, l: 10 },
      { team: "Grizzlies", w: 4, l: 10 },
      { team: "Mavericks", w: 4, l: 11 },
      { team: "Kings", w: 3, l: 11 },
      { team: "Pelicans", w: 2, l: 12 }
    ]
  }
};
